[package]
name = "unaligned-int"
version = "0.1.0"
edition = "2021"
documentation = "https://docs.rs/unaligned-int/"
description = "Unaligned integers with non-power-of-two bit widths."

[dependencies]
# none
